### ISSUE TITLE
Incompatibility with Tome & Blood Mod

### ISSUE THREAD

**Issue by Endarire** [Argent77/A7-ChaosSorcerer#2] opened 2022-06-18 16:14 UTC
Greetings, @Argent77!

subtletdoctor said that your Chaos Sorcerer mod didn't work properly with Tome & Blood if T&B is installed before it.  This seems worth fixing.

Details: https://www.gibberlings3.net/forums/topic/30797-unearthed-arcana-present-tome-blood-more-options-for-arcane-casters/?do=findComment&comment=311845

Thankee!

**Comment by Argent77** [comment] 2022-06-18 16:31
Yes, he reported it [here](http://www.shsforums.net/topic/59482-mod-the-chaos-sorcerer-a-wild-magic-kit-for-sorcerers/?p=612630) as well. The issue is already fixed internally (cfd66a4204299726511344e8d982797526623f8d). I'll release a new version shortly.

**Closed as completed by Argent77** 2022-06-18 16:31 UTC
